language: rust

rust:
  - 1.31.0
  - stable
  - beta
  - nightly

cache: cargo

script:
  - rustup component add rustfmt-preview
  - cd rboost
  - cargo fmt -- --check
  - cargo test --all

addons:
  apt:
    packages:
      - libgoogle-perftools-dev
