[package]
name = "tinygbt"
version = "0.1.0"
authors = ["Matthieu Bizien <matthieu@databiz.io>"]
edition = "2018"

[dependencies]
nalgebra = "0.16"
ord_subset = "3"
rand = "0.5.5"

[dev-dependencies]
csv = "1"
failure = "0.1.2"