[package]
name = "tinygbt"
version = "0.1.0"
authors = ["Matthieu Bizien <matthieu@databiz.io>"]
edition = "2018"

[dependencies]
nalgebra = "0.16"
#ord_subset = "3"
ord_subset = {git= "https://github.com/Emerentius/ord_subset.git"}
rand = "0.5.5"
