[package]
name = "rboost"
version = "0.1.0"
authors = ["Matthieu Bizien <matthieu@databiz.io>"]
edition = "2018"

[dependencies]
ord_subset = "3"
rand = "0.5.5"
flame = "0.2.2"
rayon = "1.0"
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
failure = "0.1.2"
cpuprofiler = "0.0.3"
